### ISSUE TITLE
Network optimization

### ISSUE THREAD

**Issue by mysticaltech** [StarpTech/k-andy#3]
Hello @StarpTech, well done, this is one of the best projects for k3s terraform for Hetzner I've come across.  

About the network config, it is actually not taking full advantage of the capability of the Hetzner private network. So what is happening now I figure is that your current config uses the default flannel network overlay that ships with k3s, on top of the Hetzner private network. 

But it turns out that the network overlay is not needed, and as the [Hetzner team recommends](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md) in the CCM docs, it is best to **use the private network itself as native routing** for Kube, without network overlay. And this is exactly what they do in their [E2E tests for the CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager/tree/master/e2etests/), and they disable with the `--no-flannel` argument for k3s, and deploy [cilium](https://cilium.io/) instead, which has support for native routing.

All the manifests and templates used in their tests can be found here https://github.com/hetznercloud/hcloud-cloud-controller-manager/tree/master/e2etests/templates

Let me know what you think! 🙏

**Comment by StarpTech** [comment]
Hi @mysticaltech thanks for opening an issue. This sounds interesting.

Those two statements are also great https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/a0e90cae61a27892eaeb59359e1121f766b80334/e2etests/setup.go#L286-L305

If it works as before with a better CNI configuration, I'd be happy to accept a PR.

**Comment by mysticaltech** [comment]
Perfect @StarpTech, will submit a PR as soon as I have something.

**Comment by StarpTech** [comment]
Friendly ping. Are you still interested?

**Comment by mysticaltech** [comment]
@StarpTech I ended up doing a similar project with cilium. K-Andy did inspire me a lot. I will share the code as soon as I push it online so you can take whatever you want from it.

**Comment by mysticaltech** [comment]
@StarpTech Here's the repo, just pushed it https://github.com/mysticaltech/kube-hetzner, thanks for everything, and keep up the good work! 🙏

**Comment by toabi** [comment]
Cool, thanks for sharing! I did a lot of changes to k-andy the last days which might be useful for you too.

Some things which come to my mind:

- agents get constant names, if you once have to recreate a server and it will get the same name, it cannot join (I solved it by adding `random_pet` behind it
- https://github.com/mysticaltech/kube-hetzner/blob/master/variables.tf#L10-L13 can be calculated by TF: https://github.com/StarpTech/k-andy/blob/main/ssh.tf#L12-L15
- I replaced https://github.com/mysticaltech/kube-hetzner/blob/master/master.tf#L51-L57 by https://github.com/StarpTech/k-andy/blob/main/kubeconfig.tf
- Do CCM pods run on your control-plane? https://github.com/mysticaltech/kube-hetzner/blob/master/manifests/hcloud-ccm-net.yaml#L49-L50 — They didn't for me: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/226 — and when it was not running constantly e.g. when replacing all agent nodes at once it brought the cluster into a weird state.

**Comment by mysticaltech** [comment]
Interesting, thanks for that @toabi, will look into each point and let you know. Really appreciate this info 🙏
