### ISSUE TITLE
Ideas/Questions about future of this project

### ISSUE THREAD

**Issue by toabi** [StarpTech/k-andy#5]
Hello, this is a cool project and I'm evaluating to use it for more. I have a few questions:

# TF Module

Wouldn't it be nice to have this as a terraform module and expose every important value as a variable?
The target right now is playground/testing, but I think this is also a good base for more serious things.

# License

Currently this code has no License, is this on purpose?

**Comment by StarpTech** [comment]
Hi @toabi, that's a good idea. Would you like to create a PR? License is MIT.

**Comment by toabi** [comment]
Okay cool, yes I will work on this now.

How do you feel about renaming of files/resources/… - I think some things could get better names.

**Comment by toabi** [comment]
Well, all that is done :)
